### ISSUE TITLE
can not download demo bag?

### ISSUE THREAD

**Issue by JokerJohn** [melhousni/ndt_mapping_localization#1]
thanks for your work！a little  problem is that the test bag link in README seems to be invalid，i can not get the page。the link is https://drive.google.com/open?id=1pfOZXEOyyDHQaHkjz8t6-o-5oJke4x-q

**Comment by JokerJohn** [comment]
![image](https://user-images.githubusercontent.com/25702851/64096495-697a7e00-cd94-11e9-937d-f77403fe6cb9.png)

**Comment by melhousni** [comment]
Sorry about that. I have updated the link
